### PR TITLE
Added upstreams option to _base template

### PR DESCRIPTION
**Pull request by elboletaire**

### CODE REVIEW

**Comment by HanXHX** [comment]
Hi @elboletaire,

Thank-you for your PR. Before integrate your commit, can you add doc in README.md please?

Cheers!

Emilien

**Comment by elboletaire** [comment]
Sure! I'll do it in a few hours. I'm also creating a "proxy" template, for proxified apps. I'll also make a PR whenever I have it :)

**Comment by HanXHX** [comment]
Great! :+1:

**Comment by HanXHX** [comment]
Hi @elboletaire 

Can you merge my master branch to yours before push? I just fixed travis.

**Comment by elboletaire** [comment]
I've not have enough time yet to do changes but sure, I'll do it :)

**Comment by HanXHX** [comment]
Hi @elboletaire 

I worked on my own implementation of proxy (see last commits). I close your PR. But thak-you for your idea. I need soms feedback sbefore release a new version.

**Comment by elboletaire** [comment]
I can see you've added the part on the virtualhost for the proxy_pass, but you've not created a space for upstreams, or maybe am I wrong?

**Comment by HanXHX** [comment]
Upstreams are not a part of vhost. Read the doc! ;)

**Comment by elboletaire** [comment]
hahaha ok sorry for that

nice then ;D

**Comment by elboletaire** [comment]
@HanXHX can you please release a new version? the 1.0.2 does not have this changes on it https://github.com/HanXHX/ansible-nginx/blob/95e2cb5f12f7d5898704fbfbf953348dad238ca7/tasks/upstream.yml and using ansible-galaxy there's no way to download dev-master (or I did not found it)

**Pull request closed without merging**
